In [1]:
import ncaa_scrape as ncaa
import pandas as pd
import metrics

In [2]:
metrics.add_pitching_metrics(ncaa.get_career_stats(2111716, 'pitching'))

,school_id,GP,G,App,GS,ERA,IP,CG,H,R,...,OBP-against,BA-against,SLG-against,OPS-against,K/PA,K/9,BB/PA,BB/9,BABIP-against,FIP
0,167,11,11,11,0,4.50,12.0,0.0,15,6,...,0.404,0.333,0.400,0.804,0.135,5.250,0.115,1.038,0.326,4.174
1,167,3,3,3,0,7.94,5.2,0.0,7,6,...,0.385,0.304,0.522,0.907,0.308,12.706,0.115,1.038,0.353,5.105
2,167,3,3,3,2,20.57,7.0,0.0,13,17,...,0.574,0.394,0.758,1.332,0.064,3.857,0.191,1.723,0.244,14.195

In [3]:
ncaa.get_career_stats(2111716, 'pitching')

,school_id,GP,G,App,GS,ERA,IP,CG,H,R,...,SHA,SFA,Pitches,GO,FO,W,L,SV,KL,season
0,167,11,11,11,0,4.50,12.0,0.0,15,6,...,0,1,171,11,13,0.0,0.0,0.0,4,2018
1,167,3,3,3,0,7.94,5.2,0.0,7,6,...,0,0,69,3,5,0.0,0.0,0.0,3,2019
2,167,3,3,3,2,20.57,7.0,0.0,13,17,...,2,0,175,9,7,0.0,2,0.0,0.0,2021

In [4]:
ncaa.lookup_seasons_played(2111724)

(2019, 2021)

In [5]:
metrics.add_pitching_metrics(ncaa.get_team_stats("cornell", 2019, "pitching"))

,Jersey,name,Yr,pos,GP,GS,App,GS,ERA,IP,...,OBP-against,BA-against,SLG-against,OPS-against,K/PA,K/9,BB/PA,BB/9,BABIP-against,FIP
10,34,John Natoli,Jr,P,19,1,19,1,1.73,36.1,...,0.248,0.176,0.199,0.447,0.309,11.395,0.060,0.544,0.231,2.400
11,1,Nikolas Lillios,Fr,P,15,5,9,0,3.27,11.0,...,0.333,0.300,0.375,0.708,0.089,3.273,0.067,0.600,0.279,4.042
13,32,Jon Zacharias,Fr,P,13,8,13,8,2.83,41.1,...,0.316,0.247,0.313,0.629,0.172,6.532,0.080,0.724,0.247,4.121
18,8,Kevin Cushing,Fr,P,11,0,11,0,4.50,12.0,...,0.404,0.333,0.400,0.804,0.135,5.250,0.115,1.038,0.326,4.284
15,31,Colby Wyatt,Jr,P,13,10,13,10,3.68,63.2,...,0.340,0.290,0.405,0.745,0.124,4.948,0.064,0.574,0.285,4.552
22,20,Seth Urbon,Jr,P,7,7,7,7,8.10,33.1,...,0.363,0.329,0.514,0.877,0.185,7.830,0.038,0.344,0.352,4.585
17,22,Jeb Bemiss,Jr,P,12,6,12,6,5.83,46.1,...,0.323,0.291,0.460,0.783,0.194,7.576,0.035,0.313,0.314,4.602
19,40,Andrew Ellison,Jr,P,11,2,11,2,2.39,26.1,...,0.342,0.191,0.266,0.608,0.145,5.810,0.145,1.308,0.172,5.675
12,26,Trevor Daniel Davis,So,P,14,0,14,0,4.96,16.1,...,0.400,0.290,0.449,0.849,0.212,9.918,0.118,1.059,0.269,5.752
14,12,Luke Yacinich,Fr,P,13,4,13,4,8.07,32.1,...,0.435,0.336,0.474,0.909,0.112,5.010,0.124,1.118,0.307,6.194
20,16,Austin Arnold,Sr,P,8,0,8,0,3.18,5.2,...,0.407,0.250,0.450,0.857,0.111,4.765,0.111,1.000,0.167,8.759
25,27,William Gilbert,Fr,P,2,0,2,0,5.40,1.2,...,0.556,0.200,0.200,0.756,0.333,16.200,0.444,4.000,0.167,8.951

In [6]:
ncaa.get_career_stats(2111724, 'pitching').iloc[0].IP

32.1

In [7]:
metrics.calculate_fip(ncaa.get_career_stats(2111724, 'pitching').iloc[0])

6.084

In [8]:
ncaa.lookup_player_id("Jake Gelof", "Virginia")

2486499

In [11]:
ncaa.get_career_stats(1884390, 'pitching')

,school_id,GP,G,App,GS,ERA,IP,CG,H,R,...,SHA,SFA,Pitches,GO,FO,W,L,SV,KL,season
0,167,13,0,13,0,4.76,22.2,0.0,29,14,...,2,2,291,19,33,1,2,1,6,2016
1,167,15,0,15,2,6.16,30.2,0.0,39,26,...,0,0,253,33,29,2,2,1,10,2017
2,167,12,0,12,6,5.83,46.1,1,55,32,...,2,0,376,50,46,2,3,0.0,9,2018

In [10]:
ncaa.get_roster('cornell', 2018)

,jersey,stats_player_seq,name,position,class_year,games_played,games_started
0,25,1997329,"Apostle, Jason",OF,Fr,24,19
1,6,1779078,"Arndt, Josh",INF,Jr,32,27
2,16,1779080,"Arnold, Austin",P,Jr,3,0
3,29,1997331,"Bailey, Garrett",P,Fr,4,0
4,35,1652419,"Baur, Trey",INF,Sr,26,22
5,22,1884390,"Bemiss, Jeb",P,So,15,2
6,8,1997325,"Binnie, Nicholas",P,Fr,2,0
7,2,1652397,"Bitar, Ellis",C,Sr,36,36
8,3,1884385,"Carnegie, Alex",INF,So,1,1
9,37,1884387,"Cintron, Nick",P,So,0,0
10,15,1884388,"Collins, Matt",INF,So,19,13
11,26,1997345,"Davis, Trevor",P,Fr,4,0
12,40,1997332,"Ellison, Andrew",P,So,16,0
13,23,1652394,"Fernandez, Tyler",P,Sr,9,5
14,27,1884386,"Gallagher, Kyle",OF,Sr,37,37
15,21,1997328,"Garza, Ramon",INF,Fr,27,23
16,17,1997326,"Giuliano, Dave",OF,Fr,0,0
17,12,1884383,"Krainz, Ryan",INF,Sr,37,37
18,1,1652421,"Le Dorze, Pierre",OF,Sr,19,13
19,19,1884384,"Lepper, Kaleb",OF,So,27,23
20,32,1997347,"Matton, Kalani",INF,Fr,16,10
21,7,1778328,"McMenamy, Owen",P,Jr,5,0
22,9,1884404,"Morris, Tommy",P,Sr,9,5
23,28,None,"Mottesi, Nico",OF,Fr,0,0
24,4,1884378,"Natoli, John",P,So,1,0
25,13,1779079,"Saks, Adam",P,Jr,13,3
26,30,None,"Sartor, Price",P,Fr,0,0
27,33,1779085,"Simoneit, William",C,Jr,37,37
28,38,None,"Snipes, Jaxon",OF,Fr,0,0
29,20,1997324,"Urbon, Seth",P,So,12,10
30,11,1783016,"Wahl, Austin",P,Sr,16,1
31,5,1652396,"Wickham, Dale",OF,Sr,36,35
32,36,1547000,"Willittes, Tim",P,Sr,11,11
33,31,1884389,"Wyatt, Colby",P,So,19,0